api:
  board-service:
    host: localhost
    port: 8181
    endpoint:
      getById: /boards/{id}
      getAll: /boards
      search: /boards/search
  order-service:
    host: localhost
    port: 8182
  user-service:
    host: localhost
    port: 8183
  keycloak:
    host: localhost
    port: 8184
